package com.mml.entity;
// Generated 2016-7-7 16:21:12 by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoryb generated by hbm2java
 */
@Entity
@Table(name = "categoryb", catalog = "mml")
public class Categoryb implements java.io.Serializable {

	private Integer categoryBid;
	private Categorya categorya;
	private String categoryBname;
	private Set<Goods> goodses = new HashSet<Goods>(0);

	public Categoryb() {
	}

	public Categoryb(Categorya categorya, String categoryBname) {
		this.categorya = categorya;
		this.categoryBname = categoryBname;
	}

	public Categoryb(Categorya categorya, String categoryBname, Set<Goods> goodses) {
		this.categorya = categorya;
		this.categoryBname = categoryBname;
		this.goodses = goodses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CategoryBID", unique = true, nullable = false)
	public Integer getCategoryBid() {
		return this.categoryBid;
	}

	public void setCategoryBid(Integer categoryBid) {
		this.categoryBid = categoryBid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CategoryAID", nullable = false)
	public Categorya getCategorya() {
		return this.categorya;
	}

	public void setCategorya(Categorya categorya) {
		this.categorya = categorya;
	}

	@Column(name = "CategoryBName", nullable = false, length = 10)
	public String getCategoryBname() {
		return this.categoryBname;
	}

	public void setCategoryBname(String categoryBname) {
		this.categoryBname = categoryBname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoryb")
	public Set<Goods> getGoodses() {
		return this.goodses;
	}

	public void setGoodses(Set<Goods> goodses) {
		this.goodses = goodses;
	}

}
