package com.mml.entity;
// Generated 2016-7-7 16:21:12 by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chart generated by hbm2java
 */
@Entity
@Table(name = "chart", catalog = "mml")
public class Chart implements java.io.Serializable {

	private ChartId id;
	private Goods goods;
	private Seller seller;
	private Memberuser memberuser;

	public Chart() {
	}

	public Chart(ChartId id, Goods goods, Seller seller, Memberuser memberuser) {
		this.id = id;
		this.goods = goods;
		this.seller = seller;
		this.memberuser = memberuser;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "MId", column = @Column(name = "m_ID", nullable = false)),
			@AttributeOverride(name = "GId", column = @Column(name = "g_ID", nullable = false)),
			@AttributeOverride(name = "SId", column = @Column(name = "s_ID", nullable = false)),
			@AttributeOverride(name = "chartChoseNumber", column = @Column(name = "chart_ChoseNumber", nullable = false)) })
	public ChartId getId() {
		return this.id;
	}

	public void setId(ChartId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "g_ID", nullable = false, insertable = false, updatable = false)
	public Goods getGoods() {
		return this.goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "s_ID", nullable = false, insertable = false, updatable = false)
	public Seller getSeller() {
		return this.seller;
	}

	public void setSeller(Seller seller) {
		this.seller = seller;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "m_ID", nullable = false, insertable = false, updatable = false)
	public Memberuser getMemberuser() {
		return this.memberuser;
	}

	public void setMemberuser(Memberuser memberuser) {
		this.memberuser = memberuser;
	}

}
