package com.mml.entity;
// Generated 2016-7-7 16:21:12 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChartId generated by hbm2java
 */
@Embeddable
public class ChartId implements java.io.Serializable {

	private int MId;
	private int GId;
	private int SId;
	private int chartChoseNumber;

	public ChartId() {
	}

	public ChartId(int MId, int GId, int SId, int chartChoseNumber) {
		this.MId = MId;
		this.GId = GId;
		this.SId = SId;
		this.chartChoseNumber = chartChoseNumber;
	}

	@Column(name = "m_ID", nullable = false)
	public int getMId() {
		return this.MId;
	}

	public void setMId(int MId) {
		this.MId = MId;
	}

	@Column(name = "g_ID", nullable = false)
	public int getGId() {
		return this.GId;
	}

	public void setGId(int GId) {
		this.GId = GId;
	}

	@Column(name = "s_ID", nullable = false)
	public int getSId() {
		return this.SId;
	}

	public void setSId(int SId) {
		this.SId = SId;
	}

	@Column(name = "chart_ChoseNumber", nullable = false)
	public int getChartChoseNumber() {
		return this.chartChoseNumber;
	}

	public void setChartChoseNumber(int chartChoseNumber) {
		this.chartChoseNumber = chartChoseNumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChartId))
			return false;
		ChartId castOther = (ChartId) other;

		return (this.getMId() == castOther.getMId()) && (this.getGId() == castOther.getGId())
				&& (this.getSId() == castOther.getSId())
				&& (this.getChartChoseNumber() == castOther.getChartChoseNumber());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMId();
		result = 37 * result + this.getGId();
		result = 37 * result + this.getSId();
		result = 37 * result + this.getChartChoseNumber();
		return result;
	}

}
