package com.mml.entity;
// Generated 2016-7-7 16:21:12 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "mml")
public class Comment implements java.io.Serializable {

	private Integer commentId;
	private Goods goods;
	private Seller seller;
	private Memberuser memberuser;
	private String comments;
	private String memberOrSeller;
	private Date commentTime;

	public Comment() {
	}

	public Comment(Goods goods, Seller seller, Memberuser memberuser, String comments, String memberOrSeller,
			Date commentTime) {
		this.goods = goods;
		this.seller = seller;
		this.memberuser = memberuser;
		this.comments = comments;
		this.memberOrSeller = memberOrSeller;
		this.commentTime = commentTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "comment_ID", unique = true, nullable = false)
	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "g_ID", nullable = false)
	public Goods getGoods() {
		return this.goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "s_ID", nullable = false)
	public Seller getSeller() {
		return this.seller;
	}

	public void setSeller(Seller seller) {
		this.seller = seller;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "m_ID", nullable = false)
	public Memberuser getMemberuser() {
		return this.memberuser;
	}

	public void setMemberuser(Memberuser memberuser) {
		this.memberuser = memberuser;
	}

	@Column(name = "comments", nullable = false, length = 200)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "memberOrSeller", nullable = false, length = 7)
	public String getMemberOrSeller() {
		return this.memberOrSeller;
	}

	public void setMemberOrSeller(String memberOrSeller) {
		this.memberOrSeller = memberOrSeller;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "comment_Time", nullable = false, length = 19)
	public Date getCommentTime() {
		return this.commentTime;
	}

	public void setCommentTime(Date commentTime) {
		this.commentTime = commentTime;
	}

}
