package com.mml.entity;
// Generated 2016-7-7 16:21:12 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Coupon generated by hbm2java
 */
@Entity
@Table(name = "coupon", catalog = "mml")
public class Coupon implements java.io.Serializable {

	private Integer CId;
	private int CNumber;
	private BigDecimal CLimit;
	private BigDecimal CPrice;
	private Set<Couponget> coupongets = new HashSet<Couponget>(0);

	public Coupon() {
	}

	public Coupon(int CNumber) {
		this.CNumber = CNumber;
	}

	public Coupon(int CNumber, BigDecimal CLimit, BigDecimal CPrice, Set<Couponget> coupongets) {
		this.CNumber = CNumber;
		this.CLimit = CLimit;
		this.CPrice = CPrice;
		this.coupongets = coupongets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "c_ID", unique = true, nullable = false)
	public Integer getCId() {
		return this.CId;
	}

	public void setCId(Integer CId) {
		this.CId = CId;
	}

	@Column(name = "c_Number", nullable = false)
	public int getCNumber() {
		return this.CNumber;
	}

	public void setCNumber(int CNumber) {
		this.CNumber = CNumber;
	}

	@Column(name = "c_Limit", precision = 10)
	public BigDecimal getCLimit() {
		return this.CLimit;
	}

	public void setCLimit(BigDecimal CLimit) {
		this.CLimit = CLimit;
	}

	@Column(name = "c_Price", precision = 10)
	public BigDecimal getCPrice() {
		return this.CPrice;
	}

	public void setCPrice(BigDecimal CPrice) {
		this.CPrice = CPrice;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coupon")
	public Set<Couponget> getCoupongets() {
		return this.coupongets;
	}

	public void setCoupongets(Set<Couponget> coupongets) {
		this.coupongets = coupongets;
	}

}
