package com.mml.entity;
// Generated 2016-7-7 16:21:12 by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Couponget generated by hbm2java
 */
@Entity
@Table(name = "couponget", catalog = "mml")
public class Couponget implements java.io.Serializable {

	private CoupongetId id;
	private Coupon coupon;
	private Memberuser memberuser;

	public Couponget() {
	}

	public Couponget(CoupongetId id, Coupon coupon, Memberuser memberuser) {
		this.id = id;
		this.coupon = coupon;
		this.memberuser = memberuser;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "CId", column = @Column(name = "c_ID", nullable = false)),
			@AttributeOverride(name = "MId", column = @Column(name = "m_ID", nullable = false)) })
	public CoupongetId getId() {
		return this.id;
	}

	public void setId(CoupongetId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_ID", nullable = false, insertable = false, updatable = false)
	public Coupon getCoupon() {
		return this.coupon;
	}

	public void setCoupon(Coupon coupon) {
		this.coupon = coupon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "m_ID", nullable = false, insertable = false, updatable = false)
	public Memberuser getMemberuser() {
		return this.memberuser;
	}

	public void setMemberuser(Memberuser memberuser) {
		this.memberuser = memberuser;
	}

}
