package com.mml.entity;
// Generated 2016-7-7 16:21:12 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CoupongetId generated by hbm2java
 */
@Embeddable
public class CoupongetId implements java.io.Serializable {

	private int CId;
	private int MId;

	public CoupongetId() {
	}

	public CoupongetId(int CId, int MId) {
		this.CId = CId;
		this.MId = MId;
	}

	@Column(name = "c_ID", nullable = false)
	public int getCId() {
		return this.CId;
	}

	public void setCId(int CId) {
		this.CId = CId;
	}

	@Column(name = "m_ID", nullable = false)
	public int getMId() {
		return this.MId;
	}

	public void setMId(int MId) {
		this.MId = MId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CoupongetId))
			return false;
		CoupongetId castOther = (CoupongetId) other;

		return (this.getCId() == castOther.getCId()) && (this.getMId() == castOther.getMId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCId();
		result = 37 * result + this.getMId();
		return result;
	}

}
