package com.mml.entity;
// Generated 2016-7-7 16:21:12 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Discount generated by hbm2java
 */
@Entity
@Table(name = "discount", catalog = "mml")
public class Discount implements java.io.Serializable {

	private Integer DId;
	private BigDecimal DDiscount;
	private int SId;

	public Discount() {
	}

	public Discount(BigDecimal DDiscount, int SId) {
		this.DDiscount = DDiscount;
		this.SId = SId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "d_ID", unique = true, nullable = false)
	public Integer getDId() {
		return this.DId;
	}

	public void setDId(Integer DId) {
		this.DId = DId;
	}

	@Column(name = "d_Discount", nullable = false, precision = 3)
	public BigDecimal getDDiscount() {
		return this.DDiscount;
	}

	public void setDDiscount(BigDecimal DDiscount) {
		this.DDiscount = DDiscount;
	}

	@Column(name = "s_ID", nullable = false)
	public int getSId() {
		return this.SId;
	}

	public void setSId(int SId) {
		this.SId = SId;
	}

}
