package com.mml.entity;
// Generated 2016-7-7 16:21:12 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fullcut generated by hbm2java
 */
@Entity
@Table(name = "fullcut", catalog = "mml")
public class Fullcut implements java.io.Serializable {

	private Integer FId;
	private int SId;
	private BigDecimal FFull;
	private BigDecimal FCut;

	public Fullcut() {
	}

	public Fullcut(int SId, BigDecimal FFull, BigDecimal FCut) {
		this.SId = SId;
		this.FFull = FFull;
		this.FCut = FCut;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "f_ID", unique = true, nullable = false)
	public Integer getFId() {
		return this.FId;
	}

	public void setFId(Integer FId) {
		this.FId = FId;
	}

	@Column(name = "s_ID", nullable = false)
	public int getSId() {
		return this.SId;
	}

	public void setSId(int SId) {
		this.SId = SId;
	}

	@Column(name = "f_Full", nullable = false, precision = 10)
	public BigDecimal getFFull() {
		return this.FFull;
	}

	public void setFFull(BigDecimal FFull) {
		this.FFull = FFull;
	}

	@Column(name = "f_Cut", nullable = false, precision = 10)
	public BigDecimal getFCut() {
		return this.FCut;
	}

	public void setFCut(BigDecimal FCut) {
		this.FCut = FCut;
	}

}
