package com.mml.entity;
// Generated 2016-7-7 16:21:12 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Gift generated by hbm2java
 */
@Entity
@Table(name = "gift", catalog = "mml")
public class Gift implements java.io.Serializable {

	private Integer giftId;
	private Goods goods;
	private Seller seller;
	private BigDecimal giftLimit;

	public Gift() {
	}

	public Gift(Goods goods, Seller seller) {
		this.goods = goods;
		this.seller = seller;
	}

	public Gift(Goods goods, Seller seller, BigDecimal giftLimit) {
		this.goods = goods;
		this.seller = seller;
		this.giftLimit = giftLimit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "gift_ID", unique = true, nullable = false)
	public Integer getGiftId() {
		return this.giftId;
	}

	public void setGiftId(Integer giftId) {
		this.giftId = giftId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "g_ID", nullable = false)
	public Goods getGoods() {
		return this.goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "s_ID", nullable = false)
	public Seller getSeller() {
		return this.seller;
	}

	public void setSeller(Seller seller) {
		this.seller = seller;
	}

	@Column(name = "gift_Limit", precision = 10)
	public BigDecimal getGiftLimit() {
		return this.giftLimit;
	}

	public void setGiftLimit(BigDecimal giftLimit) {
		this.giftLimit = giftLimit;
	}

}
