package com.mml.entity;
// Generated 2016-7-7 16:21:12 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Goods generated by hbm2java
 */
@Entity
@Table(name = "goods", catalog = "mml")
public class Goods implements java.io.Serializable {

	private Integer GId;
	private Seller seller;
	private Categorya categorya;
	private Categoryb categoryb;
	private String GName;
	private BigDecimal GPrice;
	private String GPicture;
	private String GDescription;
	private String GTag;
	private Date GUpdateTime;
	private int GNumber;
	private int GSales;
	private int GClick;
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<Gift> gifts = new HashSet<Gift>(0);
	private Set<Orders> orderses = new HashSet<Orders>(0);
	private Set<Chart> charts = new HashSet<Chart>(0);

	public Goods() {
	}

	public Goods(Seller seller, Categorya categorya, Categoryb categoryb, String GName, BigDecimal GPrice,
			String GPicture, String GDescription, String GTag, Date GUpdateTime, int GNumber, int GSales, int GClick) {
		this.seller = seller;
		this.categorya = categorya;
		this.categoryb = categoryb;
		this.GName = GName;
		this.GPrice = GPrice;
		this.GPicture = GPicture;
		this.GDescription = GDescription;
		this.GTag = GTag;
		this.GUpdateTime = GUpdateTime;
		this.GNumber = GNumber;
		this.GSales = GSales;
		this.GClick = GClick;
	}

	public Goods(Seller seller, Categorya categorya, Categoryb categoryb, String GName, BigDecimal GPrice,
			String GPicture, String GDescription, String GTag, Date GUpdateTime, int GNumber, int GSales, int GClick,
			Set<Comment> comments, Set<Gift> gifts, Set<Orders> orderses, Set<Chart> charts) {
		this.seller = seller;
		this.categorya = categorya;
		this.categoryb = categoryb;
		this.GName = GName;
		this.GPrice = GPrice;
		this.GPicture = GPicture;
		this.GDescription = GDescription;
		this.GTag = GTag;
		this.GUpdateTime = GUpdateTime;
		this.GNumber = GNumber;
		this.GSales = GSales;
		this.GClick = GClick;
		this.comments = comments;
		this.gifts = gifts;
		this.orderses = orderses;
		this.charts = charts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "g_ID", unique = true, nullable = false)
	public Integer getGId() {
		return this.GId;
	}

	public void setGId(Integer GId) {
		this.GId = GId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "s_ID", nullable = false)
	public Seller getSeller() {
		return this.seller;
	}

	public void setSeller(Seller seller) {
		this.seller = seller;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CategoryAID", nullable = false)
	public Categorya getCategorya() {
		return this.categorya;
	}

	public void setCategorya(Categorya categorya) {
		this.categorya = categorya;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CategoryBID", nullable = false)
	public Categoryb getCategoryb() {
		return this.categoryb;
	}

	public void setCategoryb(Categoryb categoryb) {
		this.categoryb = categoryb;
	}

	@Column(name = "g_Name", nullable = false, length = 10)
	public String getGName() {
		return this.GName;
	}

	public void setGName(String GName) {
		this.GName = GName;
	}

	@Column(name = "g_Price", nullable = false, precision = 10)
	public BigDecimal getGPrice() {
		return this.GPrice;
	}

	public void setGPrice(BigDecimal GPrice) {
		this.GPrice = GPrice;
	}

	@Column(name = "g_Picture", nullable = false, length = 50)
	public String getGPicture() {
		return this.GPicture;
	}

	public void setGPicture(String GPicture) {
		this.GPicture = GPicture;
	}

	@Column(name = "g_Description", nullable = false, length = 100)
	public String getGDescription() {
		return this.GDescription;
	}

	public void setGDescription(String GDescription) {
		this.GDescription = GDescription;
	}

	@Column(name = "g_Tag", nullable = false, length = 10)
	public String getGTag() {
		return this.GTag;
	}

	public void setGTag(String GTag) {
		this.GTag = GTag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "g_UpdateTime", nullable = false, length = 19)
	public Date getGUpdateTime() {
		return this.GUpdateTime;
	}

	public void setGUpdateTime(Date GUpdateTime) {
		this.GUpdateTime = GUpdateTime;
	}

	@Column(name = "g_Number", nullable = false)
	public int getGNumber() {
		return this.GNumber;
	}

	public void setGNumber(int GNumber) {
		this.GNumber = GNumber;
	}

	@Column(name = "g_Sales", nullable = false)
	public int getGSales() {
		return this.GSales;
	}

	public void setGSales(int GSales) {
		this.GSales = GSales;
	}

	@Column(name = "g_Click", nullable = false)
	public int getGClick() {
		return this.GClick;
	}

	public void setGClick(int GClick) {
		this.GClick = GClick;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
	public Set<Gift> getGifts() {
		return this.gifts;
	}

	public void setGifts(Set<Gift> gifts) {
		this.gifts = gifts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
	public Set<Chart> getCharts() {
		return this.charts;
	}

	public void setCharts(Set<Chart> charts) {
		this.charts = charts;
	}

}
