package com.mml.entity;
// Generated 2016-7-7 16:21:12 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "mml")
public class Orders implements java.io.Serializable {

	private Integer OId;
	private Goods goods;
	private Memberuser memberuser;
	private BigDecimal OTotalPrice;
	private String OReceiveState;
	private String OPayState;
	private String OPayWay;
	private Date OTime;

	public Orders() {
	}

	public Orders(Goods goods, Memberuser memberuser, BigDecimal OTotalPrice, String OReceiveState, String OPayState,
			Date OTime) {
		this.goods = goods;
		this.memberuser = memberuser;
		this.OTotalPrice = OTotalPrice;
		this.OReceiveState = OReceiveState;
		this.OPayState = OPayState;
		this.OTime = OTime;
	}

	public Orders(Goods goods, Memberuser memberuser, BigDecimal OTotalPrice, String OReceiveState, String OPayState,
			String OPayWay, Date OTime) {
		this.goods = goods;
		this.memberuser = memberuser;
		this.OTotalPrice = OTotalPrice;
		this.OReceiveState = OReceiveState;
		this.OPayState = OPayState;
		this.OPayWay = OPayWay;
		this.OTime = OTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "o_ID", unique = true, nullable = false)
	public Integer getOId() {
		return this.OId;
	}

	public void setOId(Integer OId) {
		this.OId = OId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "g_ID", nullable = false)
	public Goods getGoods() {
		return this.goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "m_ID", nullable = false)
	public Memberuser getMemberuser() {
		return this.memberuser;
	}

	public void setMemberuser(Memberuser memberuser) {
		this.memberuser = memberuser;
	}

	@Column(name = "o_TotalPrice", nullable = false, precision = 10)
	public BigDecimal getOTotalPrice() {
		return this.OTotalPrice;
	}

	public void setOTotalPrice(BigDecimal OTotalPrice) {
		this.OTotalPrice = OTotalPrice;
	}

	@Column(name = "o_ReceiveState", nullable = false, length = 2)
	public String getOReceiveState() {
		return this.OReceiveState;
	}

	public void setOReceiveState(String OReceiveState) {
		this.OReceiveState = OReceiveState;
	}

	@Column(name = "o_PayState", nullable = false, length = 2)
	public String getOPayState() {
		return this.OPayState;
	}

	public void setOPayState(String OPayState) {
		this.OPayState = OPayState;
	}

	@Column(name = "o_PayWay", length = 5)
	public String getOPayWay() {
		return this.OPayWay;
	}

	public void setOPayWay(String OPayWay) {
		this.OPayWay = OPayWay;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "o_Time", nullable = false, length = 19)
	public Date getOTime() {
		return this.OTime;
	}

	public void setOTime(Date OTime) {
		this.OTime = OTime;
	}

}
