package com.mml.entity;
// Generated 2016-7-7 16:21:12 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promotion generated by hbm2java
 */
@Entity
@Table(name = "promotion", catalog = "mml")
public class Promotion implements java.io.Serializable {

	private Integer PId;
	private Date PStartTime;
	private Date PEndTime;
	private String PPost;

	public Promotion() {
	}

	public Promotion(Date PStartTime, Date PEndTime, String PPost) {
		this.PStartTime = PStartTime;
		this.PEndTime = PEndTime;
		this.PPost = PPost;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "p_ID", unique = true, nullable = false)
	public Integer getPId() {
		return this.PId;
	}

	public void setPId(Integer PId) {
		this.PId = PId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "p_StartTime", nullable = false, length = 19)
	public Date getPStartTime() {
		return this.PStartTime;
	}

	public void setPStartTime(Date PStartTime) {
		this.PStartTime = PStartTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "p_EndTime", nullable = false, length = 19)
	public Date getPEndTime() {
		return this.PEndTime;
	}

	public void setPEndTime(Date PEndTime) {
		this.PEndTime = PEndTime;
	}

	@Column(name = "p_Post", nullable = false, length = 50)
	public String getPPost() {
		return this.PPost;
	}

	public void setPPost(String PPost) {
		this.PPost = PPost;
	}

}
